export {
  useGafpriApiEntity,
  useGafpriAttributesEntity,
  useGafpriDataEntity,
  useGafpriPaginationsEntity,
  useGafpriPagesEntity,
} from './entity';
export type {
  UseGafpriApiEntityReturn,
  UseGafpriApiEntityProps,
  UseGafpriAttributesEntityReturn,
  typeDocumentId,
  DocumentIdAttributes,
  AddressAttributes,
  EntityAttributes,
  UseGafpriAttributesEntityProps,
  UseGafpriDataEntityReturn,
  UseGafpriDataEntityProps,
  UseGafpriPaginationsEntityReturn,
  UseGafpriPaginationsEntityProps,
  UseGafpriPagesEntityReturn,
  UseGafpriPagesEntityProps,
  UseGafpriApiEntityReturnDataCreate,
  UseGafpriApiEntityReturnDataUpdate,
  UseGafpriApiEntityReturnDataDelete,
} from './entity';
