export {
  useGafpriApiEntity,
  useGafpriAttributesEntity,
  useGafpriDataEntity,
  useGafpriPaginationsEntity,
  useGafpriPagesEntity,
} from './entity';
export type {
  UseGafpriApiEntityReturn,
  UseGafpriApiEntityProps,
  UseGafpriAttributesEntityReturn,
  typeDocumentId,
  DocumentIdAttributes,
  AddressAttributes,
  EntityAttributes,
  UseGafpriAttributesEntityProps,
  UseGafpriDataEntityReturn,
  UseGafpriDataEntityProps,
  UseGafpriPaginationsEntityReturn,
  UseGafpriPaginationsEntityProps,
  UseGafpriPagesEntityReturn,
  UseGafpriPagesEntityProps,
  UseGafpriApiEntityReturnDataCreate,
  UseGafpriApiEntityReturnDataUpdate,
  UseGafpriApiEntityReturnDataDelete,
} from './entity';
export {
  useGafpriAttributesProducts,
  useGafpriSubPagesProducts,
  useGafpriPagesProducts,
  useGafpriDataProducts,
  useGafpriApiProducts,
  useGafpriPaginationsProducts,
} from './products';
export type {
  UseGafpriAttributesProductsReturn,
  UseGafpriAttributesProductsProps,
  UseGafpriSubPagesProductsReturn,
  UseGafpriPagesProductsReturn,
  UseGafpriPagesProductsProps,
  UseGafpriDataProductsReturn,
  UseGafpriDataProductsProps,
  ProductsAttributes,
  UseGafpriApiProductsReturn,
  UseGafpriApiProductsProps,
  UseGafpriPaginationsProductsReturn,
  UseGafpriPaginationsProductsProps,
} from './products';
export {
  useGafpriAttributesOrderItems,
  useGafpriAttributesBudgetItems,
} from './productsItems';
export type {
  UseGafpriAttributesOrderItemsReturn,
  UseGafpriAttributesOrderItemsProps,
  OrderItemsAttributes,
  UseGafpriAttributesBudgetItemsReturn,
  UseGafpriAttributesBudgetItemsProps,
  BudgetItemsAttributes,
} from './productsItems';
export {
  useGafpriAttributesTaxClasses,
  useGafpriDataTaxClasses,
  useGafpriApiTaxClasses,
  useGafpriPaginationsTaxClasses,
  useGafpriPagesTaxClasses,
  useGafpriApiTaxRates,
  useGafpriAttributesTaxRates,
  useGafpriDataTaxRates,
  useGafpriPaginationsTaxRates,
  useGafpriPagesTaxRates,
} from './taxes';
export type {
  UseGafpriAttributesTaxClassesReturn,
  UseGafpriDataTaxClassesReturn,
  UseGafpriDataTaxClassesProps,
  TaxClassesAttributes,
  UseGafpriApiTaxClassesReturn,
  UseGafpriApiTaxClassesProps,
  UseGafpriPaginationsTaxClassesReturn,
  UseGafpriPaginationsTaxClassesProps,
  UseGafpriPagesTaxClassesReturn,
  UseGafpriPagesTaxClassesProps,
  UseGafpriAttributesTaxRatesReturn,
  UseGafpriDataTaxRatesReturn,
  UseGafpriDataTaxRatesProps,
  TaxRatesAttributes,
  UseGafpriApiTaxRatesReturn,
  UseGafpriApiTaxRatesProps,
  UseGafpriPaginationsTaxRatesReturn,
  UseGafpriPagesTaxRatesReturn,
  UseGafpriPagesTaxRatesProps,
} from './taxes';
export {
  useGafpriAttributesOrder,
  useGafpriPagesOrder,
  useGafpriApiOrder,
  useGafpriDataOrder,
  useGafpriPaginationsOrder,
} from './order';
export type {
  UseGafpriAttributesOrderReturn,
  UseGafpriAttributesOrderProps,
  UseGafpriPagesOrderReturn,
  UseGafpriPagesOrderProps,
  UseGafpriApiOrderReturn,
  UseGafpriApiOrderProps,
  UseGafpriDataOrderReturn,
  UseGafpriDataOrderProps,
  OrderAttributes,
  UseGafpriPaginationsOrderReturn,
  UseGafpriPaginationsOrderProps,
} from './order';
export { useGafpriPagesSalesModule } from './salesModule';
export type { UseGafpriPagesSalesModuleReturn } from './salesModule';
export {
  useGafpriAttributesBudget,
  useGafpriPagesBudget,
  useGafpriDataBudget,
  useGafpriPaginationsBudget,
  useGafpriApiBudget,
} from './budget';
export type {
  UseGafpriAttributesBudgetReturn,
  UseGafpriAttributesBudgetProps,
  UseGafpriPagesBudgetReturn,
  UseGafpriPagesBudgetProps,
  UseGafpriDataBudgetReturn,
  UseGafpriDataBudgetProps,
  BudgetAttributes,
  UseGafpriPaginationsBudgetReturn,
  UseGafpriPaginationsBudgetProps,
  UseGafpriApiBudgetReturn,
  UseGafpriApiBudgetProps,
} from './budget';
export {
  useGafpriAttributesShippingMethods,
  useGafpriPagesShippingMethods,
  useGafpriDataShippingMethods,
  useGafpriApiShippingMethods,
  useGafpriPaginationsShippingMethods,
  useGafpriAttributesShippingAreas,
  useGafpriPagesShippingAreas,
  useGafpriDataShippingAreas,
  useGafpriApiShippingAreas,
  useGafpriPaginationsShippingAreas,
} from './shipping';
export type {
  UseGafpriAttributesShippingMethodsReturn,
  UseGafpriPagesShippingMethodsReturn,
  UseGafpriPagesShippingMethodsProps,
  UseGafpriDataShippingMethodsReturn,
  ShippingMethodsAttributes,
  UseGafpriDataShippingMethodsProps,
  UseGafpriApiShippingMethodsReturn,
  UseGafpriApiShippingMethodsProps,
  UseGafpriPaginationsShippingMethodsReturn,
  UseGafpriAttributesShippingAreasReturn,
  UseGafpriPagesShippingAreasReturn,
  UseGafpriPagesShippingAreasProps,
  ShippingAreasAttributes,
  UseGafpriDataShippingAreasProps,
  UseGafpriDataShippingAreasReturn,
  UseGafpriApiShippingAreasReturn,
  UseGafpriApiShippingAreasProps,
  UseGafpriPaginationsShippingAreasReturn,
  UseGafpriPaginationsShippingAreasProps,
} from './shipping';
export {
  useGafpriApiProjects,
  useGafpriPagesProjects,
  useGafpriAttributesProjects,
  useGafpriDataProjects,
  useGafpriPaginationsProjects,
} from './projects';
export type {
  UseGafpriApiProjectsProps,
  UseGafpriApiProjectsReturn,
  UseGafpriPagesProjectsProps,
  UseGafpriPagesProjectsReturn,
  UseGafpriAttributesProjectsReturn,
  UseGafpriDataProjectsReturn,
  ProjectsAttributes,
  UseGafpriPaginationsProjectsProps,
  UseGafpriPaginationsProjectsReturn,
} from './projects';
