export const CATEGORY_STORAGE = 'GS_CATEGORY_V2';
export const CURRENCIES_STORAGE = 'GS_CURRENCIES_V2';
export const ENTITY_STORAGE = 'GS_ENTITY_V2';
export const ROLES_STORAGE = 'GS_ROLES_V2';
export const SITES_STORAGE = 'GS_SITES_V2';
export const TYPE_DOCUMENT_ID_STORAGE = 'GS_TYPE_DOCUMENT_ID_V2';
export const USERS_STORAGE = 'GS_USERS_V2';
